version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'testdatabase'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'Sc00b!d00'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"

  api:
    image: player-manager-api
    ports:
      - 8091:8091
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/testdatabase
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.datasource.username=testuser
      - spring.datasource.password=Sc00b!d00
    depends_on:
      - db
